# Generated by Django 4.2.16 on 2024-10-28 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.IntegerField(default=0)),
                ('environment', models.IntegerField(default=0)),
                ('economic', models.IntegerField(default=0)),
                ('create', models.IntegerField(default=0)),
                ('curious', models.IntegerField(default=0)),
                ('connection', models.IntegerField(default=0)),
                ('pillarsObjective', models.TextField(max_length=200)),
                ('targetEMObjective', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('creator', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Image',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('file', models.FileField(upload_to='uploads/')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('tension', models.IntegerField()),
                ('target', models.CharField(choices=[('AG', 'Agriculture & Life Science'), ('DI', 'Design'), ('ED', 'Education'), ('EG', 'Engineering'), ('HU', 'Humanities & Social Science'), ('NR', 'Natural Resources'), ('MA', 'Management'), ('MD', 'Medicine'), ('SC', 'Science'), ('TX', 'Textiles'), ('NA', 'Other')], default='NA', max_length=2)),
                ('levels', models.CharField(choices=[('FR', 'First-Year'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GA', 'Graduate'), ('CE', 'Continuing Education')], default='FR', max_length=2)),
                ('activityType', models.CharField(choices=[('MM', 'Micromoment (e.g., QFT, Think-Pair-Share, etc)'), ('JS', 'Jigsaw'), ('CS', 'Case Study'), ('ST', 'Storytelling'), ('PB', 'Problem Solving Studio / Problem-Based Learning'), ('SC', 'Structured Academic Controversy'), ('EL', 'Experiential Learning (hands-on, demonstration)'), ('DT', 'Design Thinking'), ('FA', 'Field Activity'), ('LC', 'Laboratory Course'), ('RM', 'Reflection / Metacognition'), ('NA', 'Other')], default='NA', max_length=2)),
                ('classSize', models.CharField(choices=[('LA', 'More than 100'), ('MD', '50-100'), ('SM', 'Less than 50')], default='LA', max_length=2)),
                ('duration', models.CharField(choices=[('SE', 'Semester-Long Project'), ('WE', 'Week-Long Project'), ('LO', 'Long (Over 4 Hours)'), ('MD', 'Medium (Half hour - 4 Hours)'), ('SH', 'Short (Half hour or less)')], default='LO', max_length=2)),
                ('format', models.CharField(choices=[('IP', 'In-Person'), ('HY', 'Hybrid'), ('VI', 'Virtual')], default='IP', max_length=2)),
                ('isApproved', models.BooleanField(default=False)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categories')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
