# Generated by Django 4.2.16 on 2024-11-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='files',
            field=models.ManyToManyField(to='app.file'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityType',
            field=models.CharField(choices=[('MM', 'Micromoment (e.g., QFT, Think-Pair-Share, etc)'), ('JS', 'Jigsaw'), ('CS', 'Case Study'), ('ST', 'Storytelling'), ('PB', 'Problem Solving Studio / Problem-Based Learning'), ('SC', 'Structured Academic Controversy'), ('EL', 'Experiential Learning (hands-on, demonstration)'), ('DT', 'Design Thinking'), ('FA', 'Field Activity'), ('LC', 'Laboratory Course'), ('RM', 'Reflection / Metacognition'), ('NA', 'Other'), ('NO', 'None')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='classSize',
            field=models.CharField(choices=[('LA', 'More than 100'), ('ME', '50-100'), ('SM', 'Less than 50'), ('NO', 'None')], default='LA', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.CharField(choices=[('SE', 'Semester-Long Project'), ('WE', 'Week-Long Project'), ('LO', 'Long (Over 4 Hours)'), ('MD', 'Medium (Half hour - 4 Hours)'), ('SH', 'Short (Half hour or less)'), ('NO', 'None')], default='LO', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='format',
            field=models.CharField(choices=[('IP', 'In-Person'), ('HY', 'Hybrid'), ('VI', 'Virtual'), ('NO', 'None')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='levels',
            field=models.CharField(choices=[('FR', 'First-Year'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GA', 'Graduate'), ('CE', 'Continuing Education'), ('NO', 'None')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target',
            field=models.CharField(choices=[('AG', 'Agriculture & Life Science'), ('DI', 'Design'), ('ED', 'Education'), ('EG', 'Engineering'), ('HU', 'Humanities & Social Science'), ('NR', 'Natural Resources'), ('MA', 'Management'), ('MD', 'Medicine'), ('SC', 'Science'), ('TX', 'Textiles'), ('NA', 'Other'), ('NO', 'None')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='categories',
            name='pillarsObjective',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='categories',
            name='targetEMObjective',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
