# Generated by Django 4.2.20 on 2025-04-09 14:20

from django.db import migrations, models

def populate_initial_data(apps, schema_editor):
    AboutPageSection = apps.get_model('app', 'AboutPageSection')
    AboutPageSection.objects.create(
        section_key='section1',
        title='What is Sustainability EDULab?',
        body='Sustainability EDULab has been designed and conceived as an exchange, educational platform for educators and instructors to share teaching and learning materials on the value tensions of sustainability.'
    )
    AboutPageSection.objects.create(
        section_key='section2',
        title='What are value tensions?',
        body='Value tensions occur when stakeholders have priorities or values that are in conflict. With respect to sustainability, value tensions may occur when unbalance or a lack of equilibrium between the three common pillars of sustainability exists.'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_populate_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(populate_initial_data),  # Adds initial data
    ]
