spring.application.name=finance-ai
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_ai
spring.datasource.username=financeuser
spring.datasource.password=financepass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
openai.api.key=${OPENAI_API_KEY:}
alphavantage.api-key=BA6D7UKIJQGUIXYI
news.api.key=9d9fd3fd-19dc-4cc9-baae-63a246a5f206
fmp.api.key=ANxXMe2MpGW83IaVXf0xQQkfAHq5ZWrh